# CRIO A IMAGEM REFERENTE A APLICAÇÃO PRINCIPAL, NO CASO A APLICAÇÃO É DJANGO, ENTÃO APLICAÇÃO PYTHON
FROM python:3.10.2-slim
# RODO UM COMANDO PARA ADICIONAR UM NOVO USUÁRIO CHAMADO PYTHON PARA NÃO UTILIZARMOS O USUÁRIO ROOT DA MÁQUINA VIRTUAL
RUN useradd -ms /bin/bash python
# UTILIZO O PIP (GERENCIADOR DE PACOTES DO PYTHON) PARA INSTALAR UM NOVO GERENCIADOR DE PACOTES, O PIPENV É UM PIP PORÉM COM A CAPACIDADE DE CRIAR PQUENOS AMBIENTES DE DESENVOLVIMENTO, PARA QUE CADA SERVIÇO TENHA SUA DEPENDENCIA PRÓPRIA
RUN pip install pipenv
# MUDAMOS O USUÁRIO DE ROOT PARA O USUÁRIO PYTHON QUE CRIAMOS ANTERIORMENTE
USER python
# SETAMOS O DIRETÓRIO EM QUE IREMOS DESENVOLVER A APLICAÇÃO DENTRO DA MÁQUINA VIRTUAL(DOCKER)
WORKDIR /home/python/app
# VAI GERAR O VIRTUAL ENV E GERAR A PASTA VENV
ENV PIPENV_VENV_IN_PROJECT=True
ENV PYTHONPATH=${PYTHONPATH}/home/python/app/src
# O TERMINAL VAI RODAR ESSES COMANDOS PARA LER INDEFINIDAMENTE(SEM PARAR) A PASTA DE DESENVOLVIMENTO
CMD [ "tail", "-f", "/dev/null"]