# Generated by Django 4.2.1 on 2023-05-22 14:40

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('release_year', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
                ('pages', models.IntegerField()),
                ('added_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('document', models.FileField(upload_to=api.models.upload_to)),
            ],
        ),
    ]
