# Generated by Django 4.2.1 on 2023-05-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_book_category_alter_author_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='books',
        ),
        migrations.AddField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='category', to='api.book'),
        ),
    ]
